<#--

    THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
    FOR A PARTICULAR PURPOSE. THIS CODE AND INFORMATION ARE NOT SUPPORTED BY XEBIALABS.

-->
FROM ${deployed.image}

RUN mkdir -p ${deployed.targetPath}
COPY ${deployed.file.name} ${deployed.targetPath}/${deployed.file.name}
VOLUME ${deployed.targetPath}

CMD ["/bin/sh"]



